import("//third_party/skia/modules/svg/svg.gni")

source_set("xenon_common_bubble") {
  sources = [
    "ui/xenon_common_bubble.cc",
    "ui/xenon_common_bubble.h",
  ]

  deps = [
    "//base",
    "//cc/paint",
    "//ui/base",
    "//ui/base:types",
    "//ui/base/mojom:ui_base_types",
    "//ui/color",
    "//ui/gfx",
    "//ui/views",
  ]
}

source_set("browser") {
  defines = []
  sources = [
    "xenon_browser_main_extra_parts.cc",
    "xenon_browser_main_extra_parts.h",
    "xenon_extension_manager.cc",
    "xenon_extension_manager.h",
    "xenon_manager.cc",
    "xenon_manager.h",

    "ui/xenon_web_dialog.cc",
    "ui/xenon_web_dialog.h",
    "ui/webui/xenon_page_handler.cc",
    "ui/webui/xenon_page_handler.h",
    "ui/webui/xenon_webui_controller.cc",
    "ui/webui/xenon_webui_controller.h",
    "ui/webui/simple_webui_controller.cc",
    "ui/webui/simple_webui_controller.h",
    "ui/svg_image_source.cc",
    "ui/svg_image_source.h",

    "reminder/xenon_reminder_types.cc",
    "reminder/xenon_reminder_types.h",
    "reminder/xenon_reminder_notification_observer.h",
    "reminder/xenon_reminder_notification_manager.cc",
    "reminder/xenon_reminder_notification_manager.h",
    "ui/xenon_reminder_card_webview.cc",
    "ui/xenon_reminder_card_webview.h",
    "ui/xenon_reminder_notification_group.cc",
    "ui/xenon_reminder_notification_group.h",
    "ui/xenon_reminder_notification_container.cc",
    "ui/xenon_reminder_notification_container.h",
    "ui/xenon_reminder_notification_widget.cc",
    "ui/xenon_reminder_notification_widget.h",
    "ui/xenon_tip_bar_widget.cc",
    "ui/xenon_tip_bar_widget.h",
    "ui/xenon_reminder_browser_observer.cc",
    "ui/xenon_reminder_browser_observer.h",
  ]

  deps = [
    "//base",
    "//chrome/browser:browser_process",
    "//chrome/browser/ui:ui",
    "//content/public/browser",
    "//ui/compositor",
    "//ui/views",
    "//services/network/public/mojom",
    "//ui/base",
    "//ui/display",
    "//ui/gfx",
    "//ui/web_dialogs",
    "//xenon_overlay/public/mojom",
    "//xenon_overlay/chrome/browser/ui/webui:mojo_bindings",
    "//xenon_overlay/resources:resources",
    "//ui/webui",
    "//mojo/public/cpp/bindings",
    "//skia",
    "//third_party/expat",
    "//extensions/browser",
    "//extensions/common",
    "//services/network/public/cpp",
    "//components/services/unzip/content",
    "//components/services/unzip/public/cpp",
  ]
}
