import("//tools/grit/grit_rule.gni")

grit("resources_grit") {
  source = "xenon_resources.grd"
  outputs = [
    "grit/xenon_resources.h",
    "xenon_resources.pak",
  ]
  deps = [ "webui:resources" ]
}

copy("copy_pak") {
  sources = [ "$target_gen_dir/xenon_resources.pak" ]
  outputs = [ "$root_out_dir/xenon_resources.pak" ]
  deps = [ ":resources_grit" ]
}

copy("copy_extension") {
  sources = [
    "extension/manifest.json",
    "extension/index.html",
    "extension/main.js",
    "extension/background.js",
  ]
  outputs = [ "$root_out_dir/resources/xenon_extension/{{source_file_part}}" ]
}

group("resources") {
  public_deps = [
    ":resources_grit",
    ":copy_pak",
    ":copy_extension",
  ]
}
