import("//tools/grit/grit_rule.gni")
import("//xenon_overlay/buildflags/features.gni")

grit("resources_grit") {
  source = "xenon_resources.grd"
  outputs = [
    "grit/xenon_resources.h",
    "xenon_resources.pak",
  ]
  deps = [ "webui:resources" ]
}

copy("copy_extension") {
  if (xenon_extension_source == "zip") {
    sources = [ "xenon_extension.zip" ]
    outputs = [ "$root_out_dir/resources/{{source_file_part}}" ]
  } else {
    sources = [
      "extension/background.js",
      "extension/index.html",
      "extension/main.js",
      "extension/manifest.json",
    ]
    outputs =
        [ "$root_out_dir/resources/xenon_extension/{{source_file_part}}" ]
  }
}

if (is_mac) {
  bundle_data("copy_extension_mac") {
    if (xenon_extension_source == "zip") {
      sources = [ "xenon_extension.zip" ]
      outputs = [ "{{bundle_resources_dir}}/resources/{{source_file_part}}" ]
    } else {
      sources = [
        "extension/background.js",
        "extension/index.html",
        "extension/main.js",
        "extension/manifest.json",
      ]
      outputs = [
        "{{bundle_resources_dir}}/resources/xenon_extension/{{source_file_part}}",
      ]
    }
  }
}

group("resources") {
  public_deps = [
    ":resources_grit",
    ":copy_extension",
  ]

  if (is_mac) {
    public_deps += [ ":copy_extension_mac" ]
  }
}
