import("//mojo/public/tools/bindings/mojom.gni")

mojom("mojom") {
  sources = [
    "xenon_ipc.mojom",
    "xenon_page_api.mojom",
    "xenon_service.mojom",
  ]
  public_deps = [
    "//mojo/public/mojom/base",
  ]
  deps = [
    "//services/network/public/mojom",
    "//sandbox/policy/mojom",
  ]
}
