#!/usr/bin/env python3
"""Embed bundled font files as C++ byte arrays."""

import argparse
from pathlib import Path

MAX_EMBED_SIZE = 1024 * 1024  # 1MB


def write_array(base_name: str, data: bytes, out_cc: list) -> None:
    out_cc.append(f"alignas(8) const uint8_t {base_name}[] = {{")
    line = "  "
    for i, byte in enumerate(data):
        if i and i % 16 == 0:
            out_cc.append(line.rstrip())
            line = "  "
        line += f"0x{byte:02x}, "
    if line.strip():
        out_cc.append(line.rstrip())
    out_cc.append("};")
    out_cc.append(f"const size_t {base_name}Size = {len(data)};")
    out_cc.append("")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-cc", required=True, type=Path)
    parser.add_argument("--out-h", required=True, type=Path)
    parser.add_argument("--regular", required=True, type=Path)
    parser.add_argument("--bold", required=True, type=Path)
    args = parser.parse_args()

    regular = args.regular.read_bytes()
    bold = args.bold.read_bytes()

    # If file size is > 1MB, write empty array (size = 0)
    regular_embed = regular if len(regular) <= MAX_EMBED_SIZE else b""
    bold_embed = bold if len(bold) <= MAX_EMBED_SIZE else b""

    header = f"""// Generated by {Path(__file__).name}. Do not edit.

#ifndef XENON_OVERLAY_XENON_CHROME_BROWSER_FONTS_XENON_FONT_EMBEDDED_DATA_H_
#define XENON_OVERLAY_XENON_CHROME_BROWSER_FONTS_XENON_FONT_EMBEDDED_DATA_H_

#include <stddef.h>
#include <stdint.h>

extern const uint8_t kXenonFontDdinRegular[];
extern const size_t kXenonFontDdinRegularSize;
extern const uint8_t kXenonFontDdinBold[];
extern const size_t kXenonFontDdinBoldSize;

#endif  // XENON_OVERLAY_XENON_CHROME_BROWSER_FONTS_XENON_FONT_EMBEDDED_DATA_H_
"""
    args.out_h.write_text(header, encoding="utf-8", newline="\n")

    cc: list[str] = [
        f"// Generated by {Path(__file__).name}. Do not edit.",
        "",
        '#include "xenon_overlay/xenon/chrome/browser/fonts/xenon_font_embedded_data.h"',
        "",
    ]
    write_array("kXenonFontDdinRegular", regular_embed, cc)
    write_array("kXenonFontDdinBold", bold_embed, cc)
    args.out_cc.write_text("\n".join(cc) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
